spring:
  application:
    name: ai-research-agent
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_research_agent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate:
          format_sql: true
    database:
        postgresql